// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package raftpb

import (
	_ "github.com/gogo/protobuf/gogoproto"
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *ConfChange) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Type":
			{
				var zb0002 int32
				zb0002, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "Type")
					return
				}
				z.Type = ConfChangeType(zb0002)
			}
		case "NodeID":
			z.NodeID, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "NodeID")
				return
			}
		case "Context":
			z.Context, err = dc.ReadBytes(z.Context)
			if err != nil {
				err = msgp.WrapError(err, "Context")
				return
			}
		case "ID":
			z.ID, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ConfChange) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "Type"
	err = en.Append(0x84, 0xa4, 0x54, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(int32(z.Type))
	if err != nil {
		err = msgp.WrapError(err, "Type")
		return
	}
	// write "NodeID"
	err = en.Append(0xa6, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.NodeID)
	if err != nil {
		err = msgp.WrapError(err, "NodeID")
		return
	}
	// write "Context"
	err = en.Append(0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Context)
	if err != nil {
		err = msgp.WrapError(err, "Context")
		return
	}
	// write "ID"
	err = en.Append(0xa2, 0x49, 0x44)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ConfChange) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "Type"
	o = append(o, 0x84, 0xa4, 0x54, 0x79, 0x70, 0x65)
	o = msgp.AppendInt32(o, int32(z.Type))
	// string "NodeID"
	o = append(o, 0xa6, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44)
	o = msgp.AppendUint64(o, z.NodeID)
	// string "Context"
	o = append(o, 0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74)
	o = msgp.AppendBytes(o, z.Context)
	// string "ID"
	o = append(o, 0xa2, 0x49, 0x44)
	o = msgp.AppendUint64(o, z.ID)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ConfChange) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Type":
			{
				var zb0002 int32
				zb0002, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Type")
					return
				}
				z.Type = ConfChangeType(zb0002)
			}
		case "NodeID":
			z.NodeID, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NodeID")
				return
			}
		case "Context":
			z.Context, bts, err = msgp.ReadBytesBytes(bts, z.Context)
			if err != nil {
				err = msgp.WrapError(err, "Context")
				return
			}
		case "ID":
			z.ID, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ConfChange) Msgsize() (s int) {
	s = 1 + 5 + msgp.Int32Size + 7 + msgp.Uint64Size + 8 + msgp.BytesPrefixSize + len(z.Context) + 3 + msgp.Uint64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ConfChangeSingle) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Type":
			{
				var zb0002 int32
				zb0002, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "Type")
					return
				}
				z.Type = ConfChangeType(zb0002)
			}
		case "NodeID":
			z.NodeID, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "NodeID")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z ConfChangeSingle) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Type"
	err = en.Append(0x82, 0xa4, 0x54, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(int32(z.Type))
	if err != nil {
		err = msgp.WrapError(err, "Type")
		return
	}
	// write "NodeID"
	err = en.Append(0xa6, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.NodeID)
	if err != nil {
		err = msgp.WrapError(err, "NodeID")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z ConfChangeSingle) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Type"
	o = append(o, 0x82, 0xa4, 0x54, 0x79, 0x70, 0x65)
	o = msgp.AppendInt32(o, int32(z.Type))
	// string "NodeID"
	o = append(o, 0xa6, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44)
	o = msgp.AppendUint64(o, z.NodeID)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ConfChangeSingle) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Type":
			{
				var zb0002 int32
				zb0002, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Type")
					return
				}
				z.Type = ConfChangeType(zb0002)
			}
		case "NodeID":
			z.NodeID, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NodeID")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ConfChangeSingle) Msgsize() (s int) {
	s = 1 + 5 + msgp.Int32Size + 7 + msgp.Uint64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ConfChangeTransition) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 int32
		zb0001, err = dc.ReadInt32()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = ConfChangeTransition(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z ConfChangeTransition) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteInt32(int32(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z ConfChangeTransition) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendInt32(o, int32(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ConfChangeTransition) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 int32
		zb0001, bts, err = msgp.ReadInt32Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = ConfChangeTransition(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ConfChangeTransition) Msgsize() (s int) {
	s = msgp.Int32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ConfChangeType) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 int32
		zb0001, err = dc.ReadInt32()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = ConfChangeType(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z ConfChangeType) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteInt32(int32(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z ConfChangeType) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendInt32(o, int32(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ConfChangeType) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 int32
		zb0001, bts, err = msgp.ReadInt32Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = ConfChangeType(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ConfChangeType) Msgsize() (s int) {
	s = msgp.Int32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ConfChangeV2) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Transition":
			{
				var zb0002 int32
				zb0002, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "Transition")
					return
				}
				z.Transition = ConfChangeTransition(zb0002)
			}
		case "Changes":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Changes")
				return
			}
			if cap(z.Changes) >= int(zb0003) {
				z.Changes = (z.Changes)[:zb0003]
			} else {
				z.Changes = make([]ConfChangeSingle, zb0003)
			}
			for za0001 := range z.Changes {
				var zb0004 uint32
				zb0004, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "Changes", za0001)
					return
				}
				for zb0004 > 0 {
					zb0004--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "Changes", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "Type":
						{
							var zb0005 int32
							zb0005, err = dc.ReadInt32()
							if err != nil {
								err = msgp.WrapError(err, "Changes", za0001, "Type")
								return
							}
							z.Changes[za0001].Type = ConfChangeType(zb0005)
						}
					case "NodeID":
						z.Changes[za0001].NodeID, err = dc.ReadUint64()
						if err != nil {
							err = msgp.WrapError(err, "Changes", za0001, "NodeID")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "Changes", za0001)
							return
						}
					}
				}
			}
		case "Context":
			z.Context, err = dc.ReadBytes(z.Context)
			if err != nil {
				err = msgp.WrapError(err, "Context")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ConfChangeV2) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "Transition"
	err = en.Append(0x83, 0xaa, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteInt32(int32(z.Transition))
	if err != nil {
		err = msgp.WrapError(err, "Transition")
		return
	}
	// write "Changes"
	err = en.Append(0xa7, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Changes)))
	if err != nil {
		err = msgp.WrapError(err, "Changes")
		return
	}
	for za0001 := range z.Changes {
		// map header, size 2
		// write "Type"
		err = en.Append(0x82, 0xa4, 0x54, 0x79, 0x70, 0x65)
		if err != nil {
			return
		}
		err = en.WriteInt32(int32(z.Changes[za0001].Type))
		if err != nil {
			err = msgp.WrapError(err, "Changes", za0001, "Type")
			return
		}
		// write "NodeID"
		err = en.Append(0xa6, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44)
		if err != nil {
			return
		}
		err = en.WriteUint64(z.Changes[za0001].NodeID)
		if err != nil {
			err = msgp.WrapError(err, "Changes", za0001, "NodeID")
			return
		}
	}
	// write "Context"
	err = en.Append(0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Context)
	if err != nil {
		err = msgp.WrapError(err, "Context")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ConfChangeV2) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "Transition"
	o = append(o, 0x83, 0xaa, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e)
	o = msgp.AppendInt32(o, int32(z.Transition))
	// string "Changes"
	o = append(o, 0xa7, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Changes)))
	for za0001 := range z.Changes {
		// map header, size 2
		// string "Type"
		o = append(o, 0x82, 0xa4, 0x54, 0x79, 0x70, 0x65)
		o = msgp.AppendInt32(o, int32(z.Changes[za0001].Type))
		// string "NodeID"
		o = append(o, 0xa6, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44)
		o = msgp.AppendUint64(o, z.Changes[za0001].NodeID)
	}
	// string "Context"
	o = append(o, 0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74)
	o = msgp.AppendBytes(o, z.Context)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ConfChangeV2) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Transition":
			{
				var zb0002 int32
				zb0002, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Transition")
					return
				}
				z.Transition = ConfChangeTransition(zb0002)
			}
		case "Changes":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Changes")
				return
			}
			if cap(z.Changes) >= int(zb0003) {
				z.Changes = (z.Changes)[:zb0003]
			} else {
				z.Changes = make([]ConfChangeSingle, zb0003)
			}
			for za0001 := range z.Changes {
				var zb0004 uint32
				zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Changes", za0001)
					return
				}
				for zb0004 > 0 {
					zb0004--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "Changes", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "Type":
						{
							var zb0005 int32
							zb0005, bts, err = msgp.ReadInt32Bytes(bts)
							if err != nil {
								err = msgp.WrapError(err, "Changes", za0001, "Type")
								return
							}
							z.Changes[za0001].Type = ConfChangeType(zb0005)
						}
					case "NodeID":
						z.Changes[za0001].NodeID, bts, err = msgp.ReadUint64Bytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Changes", za0001, "NodeID")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "Changes", za0001)
							return
						}
					}
				}
			}
		case "Context":
			z.Context, bts, err = msgp.ReadBytesBytes(bts, z.Context)
			if err != nil {
				err = msgp.WrapError(err, "Context")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ConfChangeV2) Msgsize() (s int) {
	s = 1 + 11 + msgp.Int32Size + 8 + msgp.ArrayHeaderSize + (len(z.Changes) * (13 + msgp.Int32Size + msgp.Uint64Size)) + 8 + msgp.BytesPrefixSize + len(z.Context)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ConfState) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Voters":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Voters")
				return
			}
			if cap(z.Voters) >= int(zb0002) {
				z.Voters = (z.Voters)[:zb0002]
			} else {
				z.Voters = make([]uint64, zb0002)
			}
			for za0001 := range z.Voters {
				z.Voters[za0001], err = dc.ReadUint64()
				if err != nil {
					err = msgp.WrapError(err, "Voters", za0001)
					return
				}
			}
		case "Learners":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Learners")
				return
			}
			if cap(z.Learners) >= int(zb0003) {
				z.Learners = (z.Learners)[:zb0003]
			} else {
				z.Learners = make([]uint64, zb0003)
			}
			for za0002 := range z.Learners {
				z.Learners[za0002], err = dc.ReadUint64()
				if err != nil {
					err = msgp.WrapError(err, "Learners", za0002)
					return
				}
			}
		case "VotersOutgoing":
			var zb0004 uint32
			zb0004, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "VotersOutgoing")
				return
			}
			if cap(z.VotersOutgoing) >= int(zb0004) {
				z.VotersOutgoing = (z.VotersOutgoing)[:zb0004]
			} else {
				z.VotersOutgoing = make([]uint64, zb0004)
			}
			for za0003 := range z.VotersOutgoing {
				z.VotersOutgoing[za0003], err = dc.ReadUint64()
				if err != nil {
					err = msgp.WrapError(err, "VotersOutgoing", za0003)
					return
				}
			}
		case "LearnersNext":
			var zb0005 uint32
			zb0005, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "LearnersNext")
				return
			}
			if cap(z.LearnersNext) >= int(zb0005) {
				z.LearnersNext = (z.LearnersNext)[:zb0005]
			} else {
				z.LearnersNext = make([]uint64, zb0005)
			}
			for za0004 := range z.LearnersNext {
				z.LearnersNext[za0004], err = dc.ReadUint64()
				if err != nil {
					err = msgp.WrapError(err, "LearnersNext", za0004)
					return
				}
			}
		case "AutoLeave":
			z.AutoLeave, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "AutoLeave")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ConfState) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "Voters"
	err = en.Append(0x85, 0xa6, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Voters)))
	if err != nil {
		err = msgp.WrapError(err, "Voters")
		return
	}
	for za0001 := range z.Voters {
		err = en.WriteUint64(z.Voters[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Voters", za0001)
			return
		}
	}
	// write "Learners"
	err = en.Append(0xa8, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x65, 0x72, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Learners)))
	if err != nil {
		err = msgp.WrapError(err, "Learners")
		return
	}
	for za0002 := range z.Learners {
		err = en.WriteUint64(z.Learners[za0002])
		if err != nil {
			err = msgp.WrapError(err, "Learners", za0002)
			return
		}
	}
	// write "VotersOutgoing"
	err = en.Append(0xae, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x73, 0x4f, 0x75, 0x74, 0x67, 0x6f, 0x69, 0x6e, 0x67)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.VotersOutgoing)))
	if err != nil {
		err = msgp.WrapError(err, "VotersOutgoing")
		return
	}
	for za0003 := range z.VotersOutgoing {
		err = en.WriteUint64(z.VotersOutgoing[za0003])
		if err != nil {
			err = msgp.WrapError(err, "VotersOutgoing", za0003)
			return
		}
	}
	// write "LearnersNext"
	err = en.Append(0xac, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x65, 0x72, 0x73, 0x4e, 0x65, 0x78, 0x74)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.LearnersNext)))
	if err != nil {
		err = msgp.WrapError(err, "LearnersNext")
		return
	}
	for za0004 := range z.LearnersNext {
		err = en.WriteUint64(z.LearnersNext[za0004])
		if err != nil {
			err = msgp.WrapError(err, "LearnersNext", za0004)
			return
		}
	}
	// write "AutoLeave"
	err = en.Append(0xa9, 0x41, 0x75, 0x74, 0x6f, 0x4c, 0x65, 0x61, 0x76, 0x65)
	if err != nil {
		return
	}
	err = en.WriteBool(z.AutoLeave)
	if err != nil {
		err = msgp.WrapError(err, "AutoLeave")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ConfState) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "Voters"
	o = append(o, 0x85, 0xa6, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Voters)))
	for za0001 := range z.Voters {
		o = msgp.AppendUint64(o, z.Voters[za0001])
	}
	// string "Learners"
	o = append(o, 0xa8, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x65, 0x72, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Learners)))
	for za0002 := range z.Learners {
		o = msgp.AppendUint64(o, z.Learners[za0002])
	}
	// string "VotersOutgoing"
	o = append(o, 0xae, 0x56, 0x6f, 0x74, 0x65, 0x72, 0x73, 0x4f, 0x75, 0x74, 0x67, 0x6f, 0x69, 0x6e, 0x67)
	o = msgp.AppendArrayHeader(o, uint32(len(z.VotersOutgoing)))
	for za0003 := range z.VotersOutgoing {
		o = msgp.AppendUint64(o, z.VotersOutgoing[za0003])
	}
	// string "LearnersNext"
	o = append(o, 0xac, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x65, 0x72, 0x73, 0x4e, 0x65, 0x78, 0x74)
	o = msgp.AppendArrayHeader(o, uint32(len(z.LearnersNext)))
	for za0004 := range z.LearnersNext {
		o = msgp.AppendUint64(o, z.LearnersNext[za0004])
	}
	// string "AutoLeave"
	o = append(o, 0xa9, 0x41, 0x75, 0x74, 0x6f, 0x4c, 0x65, 0x61, 0x76, 0x65)
	o = msgp.AppendBool(o, z.AutoLeave)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ConfState) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Voters":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Voters")
				return
			}
			if cap(z.Voters) >= int(zb0002) {
				z.Voters = (z.Voters)[:zb0002]
			} else {
				z.Voters = make([]uint64, zb0002)
			}
			for za0001 := range z.Voters {
				z.Voters[za0001], bts, err = msgp.ReadUint64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Voters", za0001)
					return
				}
			}
		case "Learners":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Learners")
				return
			}
			if cap(z.Learners) >= int(zb0003) {
				z.Learners = (z.Learners)[:zb0003]
			} else {
				z.Learners = make([]uint64, zb0003)
			}
			for za0002 := range z.Learners {
				z.Learners[za0002], bts, err = msgp.ReadUint64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Learners", za0002)
					return
				}
			}
		case "VotersOutgoing":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "VotersOutgoing")
				return
			}
			if cap(z.VotersOutgoing) >= int(zb0004) {
				z.VotersOutgoing = (z.VotersOutgoing)[:zb0004]
			} else {
				z.VotersOutgoing = make([]uint64, zb0004)
			}
			for za0003 := range z.VotersOutgoing {
				z.VotersOutgoing[za0003], bts, err = msgp.ReadUint64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "VotersOutgoing", za0003)
					return
				}
			}
		case "LearnersNext":
			var zb0005 uint32
			zb0005, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LearnersNext")
				return
			}
			if cap(z.LearnersNext) >= int(zb0005) {
				z.LearnersNext = (z.LearnersNext)[:zb0005]
			} else {
				z.LearnersNext = make([]uint64, zb0005)
			}
			for za0004 := range z.LearnersNext {
				z.LearnersNext[za0004], bts, err = msgp.ReadUint64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "LearnersNext", za0004)
					return
				}
			}
		case "AutoLeave":
			z.AutoLeave, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "AutoLeave")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ConfState) Msgsize() (s int) {
	s = 1 + 7 + msgp.ArrayHeaderSize + (len(z.Voters) * (msgp.Uint64Size)) + 9 + msgp.ArrayHeaderSize + (len(z.Learners) * (msgp.Uint64Size)) + 15 + msgp.ArrayHeaderSize + (len(z.VotersOutgoing) * (msgp.Uint64Size)) + 13 + msgp.ArrayHeaderSize + (len(z.LearnersNext) * (msgp.Uint64Size)) + 10 + msgp.BoolSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Entry) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Term":
			z.Term, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Term")
				return
			}
		case "Index":
			z.Index, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Index")
				return
			}
		case "Type":
			{
				var zb0002 int32
				zb0002, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "Type")
					return
				}
				z.Type = EntryType(zb0002)
			}
		case "Data":
			z.Data, err = dc.ReadBytes(z.Data)
			if err != nil {
				err = msgp.WrapError(err, "Data")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Entry) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "Term"
	err = en.Append(0x84, 0xa4, 0x54, 0x65, 0x72, 0x6d)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Term)
	if err != nil {
		err = msgp.WrapError(err, "Term")
		return
	}
	// write "Index"
	err = en.Append(0xa5, 0x49, 0x6e, 0x64, 0x65, 0x78)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Index)
	if err != nil {
		err = msgp.WrapError(err, "Index")
		return
	}
	// write "Type"
	err = en.Append(0xa4, 0x54, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(int32(z.Type))
	if err != nil {
		err = msgp.WrapError(err, "Type")
		return
	}
	// write "Data"
	err = en.Append(0xa4, 0x44, 0x61, 0x74, 0x61)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Data)
	if err != nil {
		err = msgp.WrapError(err, "Data")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Entry) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "Term"
	o = append(o, 0x84, 0xa4, 0x54, 0x65, 0x72, 0x6d)
	o = msgp.AppendUint64(o, z.Term)
	// string "Index"
	o = append(o, 0xa5, 0x49, 0x6e, 0x64, 0x65, 0x78)
	o = msgp.AppendUint64(o, z.Index)
	// string "Type"
	o = append(o, 0xa4, 0x54, 0x79, 0x70, 0x65)
	o = msgp.AppendInt32(o, int32(z.Type))
	// string "Data"
	o = append(o, 0xa4, 0x44, 0x61, 0x74, 0x61)
	o = msgp.AppendBytes(o, z.Data)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Entry) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Term":
			z.Term, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Term")
				return
			}
		case "Index":
			z.Index, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Index")
				return
			}
		case "Type":
			{
				var zb0002 int32
				zb0002, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Type")
					return
				}
				z.Type = EntryType(zb0002)
			}
		case "Data":
			z.Data, bts, err = msgp.ReadBytesBytes(bts, z.Data)
			if err != nil {
				err = msgp.WrapError(err, "Data")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Entry) Msgsize() (s int) {
	s = 1 + 5 + msgp.Uint64Size + 6 + msgp.Uint64Size + 5 + msgp.Int32Size + 5 + msgp.BytesPrefixSize + len(z.Data)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *EntryType) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 int32
		zb0001, err = dc.ReadInt32()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = EntryType(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z EntryType) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteInt32(int32(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z EntryType) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendInt32(o, int32(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *EntryType) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 int32
		zb0001, bts, err = msgp.ReadInt32Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = EntryType(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z EntryType) Msgsize() (s int) {
	s = msgp.Int32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *HardState) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Term":
			z.Term, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Term")
				return
			}
		case "Vote":
			z.Vote, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Vote")
				return
			}
		case "Commit":
			z.Commit, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Commit")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z HardState) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "Term"
	err = en.Append(0x83, 0xa4, 0x54, 0x65, 0x72, 0x6d)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Term)
	if err != nil {
		err = msgp.WrapError(err, "Term")
		return
	}
	// write "Vote"
	err = en.Append(0xa4, 0x56, 0x6f, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Vote)
	if err != nil {
		err = msgp.WrapError(err, "Vote")
		return
	}
	// write "Commit"
	err = en.Append(0xa6, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Commit)
	if err != nil {
		err = msgp.WrapError(err, "Commit")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z HardState) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "Term"
	o = append(o, 0x83, 0xa4, 0x54, 0x65, 0x72, 0x6d)
	o = msgp.AppendUint64(o, z.Term)
	// string "Vote"
	o = append(o, 0xa4, 0x56, 0x6f, 0x74, 0x65)
	o = msgp.AppendUint64(o, z.Vote)
	// string "Commit"
	o = append(o, 0xa6, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74)
	o = msgp.AppendUint64(o, z.Commit)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *HardState) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Term":
			z.Term, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Term")
				return
			}
		case "Vote":
			z.Vote, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Vote")
				return
			}
		case "Commit":
			z.Commit, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Commit")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z HardState) Msgsize() (s int) {
	s = 1 + 5 + msgp.Uint64Size + 5 + msgp.Uint64Size + 7 + msgp.Uint64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Message) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Type":
			{
				var zb0002 int32
				zb0002, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "Type")
					return
				}
				z.Type = MessageType(zb0002)
			}
		case "To":
			z.To, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "To")
				return
			}
		case "From":
			z.From, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "From")
				return
			}
		case "Term":
			z.Term, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Term")
				return
			}
		case "LogTerm":
			z.LogTerm, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "LogTerm")
				return
			}
		case "Index":
			z.Index, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Index")
				return
			}
		case "Entries":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Entries")
				return
			}
			if cap(z.Entries) >= int(zb0003) {
				z.Entries = (z.Entries)[:zb0003]
			} else {
				z.Entries = make([]Entry, zb0003)
			}
			for za0001 := range z.Entries {
				err = z.Entries[za0001].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Entries", za0001)
					return
				}
			}
		case "Commit":
			z.Commit, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Commit")
				return
			}
		case "Vote":
			z.Vote, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Vote")
				return
			}
		case "Snapshot":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Snapshot")
					return
				}
				z.Snapshot = nil
			} else {
				if z.Snapshot == nil {
					z.Snapshot = new(Snapshot)
				}
				err = z.Snapshot.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Snapshot")
					return
				}
			}
		case "Reject":
			z.Reject, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Reject")
				return
			}
		case "RejectHint":
			z.RejectHint, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "RejectHint")
				return
			}
		case "Context":
			z.Context, err = dc.ReadBytes(z.Context)
			if err != nil {
				err = msgp.WrapError(err, "Context")
				return
			}
		case "Responses":
			var zb0004 uint32
			zb0004, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Responses")
				return
			}
			if cap(z.Responses) >= int(zb0004) {
				z.Responses = (z.Responses)[:zb0004]
			} else {
				z.Responses = make([]Message, zb0004)
			}
			for za0002 := range z.Responses {
				err = z.Responses[za0002].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Responses", za0002)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Message) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 14
	// write "Type"
	err = en.Append(0x8e, 0xa4, 0x54, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(int32(z.Type))
	if err != nil {
		err = msgp.WrapError(err, "Type")
		return
	}
	// write "To"
	err = en.Append(0xa2, 0x54, 0x6f)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.To)
	if err != nil {
		err = msgp.WrapError(err, "To")
		return
	}
	// write "From"
	err = en.Append(0xa4, 0x46, 0x72, 0x6f, 0x6d)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.From)
	if err != nil {
		err = msgp.WrapError(err, "From")
		return
	}
	// write "Term"
	err = en.Append(0xa4, 0x54, 0x65, 0x72, 0x6d)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Term)
	if err != nil {
		err = msgp.WrapError(err, "Term")
		return
	}
	// write "LogTerm"
	err = en.Append(0xa7, 0x4c, 0x6f, 0x67, 0x54, 0x65, 0x72, 0x6d)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.LogTerm)
	if err != nil {
		err = msgp.WrapError(err, "LogTerm")
		return
	}
	// write "Index"
	err = en.Append(0xa5, 0x49, 0x6e, 0x64, 0x65, 0x78)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Index)
	if err != nil {
		err = msgp.WrapError(err, "Index")
		return
	}
	// write "Entries"
	err = en.Append(0xa7, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Entries)))
	if err != nil {
		err = msgp.WrapError(err, "Entries")
		return
	}
	for za0001 := range z.Entries {
		err = z.Entries[za0001].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Entries", za0001)
			return
		}
	}
	// write "Commit"
	err = en.Append(0xa6, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Commit)
	if err != nil {
		err = msgp.WrapError(err, "Commit")
		return
	}
	// write "Vote"
	err = en.Append(0xa4, 0x56, 0x6f, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Vote)
	if err != nil {
		err = msgp.WrapError(err, "Vote")
		return
	}
	// write "Snapshot"
	err = en.Append(0xa8, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74)
	if err != nil {
		return
	}
	if z.Snapshot == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.Snapshot.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Snapshot")
			return
		}
	}
	// write "Reject"
	err = en.Append(0xa6, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Reject)
	if err != nil {
		err = msgp.WrapError(err, "Reject")
		return
	}
	// write "RejectHint"
	err = en.Append(0xaa, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x48, 0x69, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.RejectHint)
	if err != nil {
		err = msgp.WrapError(err, "RejectHint")
		return
	}
	// write "Context"
	err = en.Append(0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Context)
	if err != nil {
		err = msgp.WrapError(err, "Context")
		return
	}
	// write "Responses"
	err = en.Append(0xa9, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Responses)))
	if err != nil {
		err = msgp.WrapError(err, "Responses")
		return
	}
	for za0002 := range z.Responses {
		err = z.Responses[za0002].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Responses", za0002)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Message) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 14
	// string "Type"
	o = append(o, 0x8e, 0xa4, 0x54, 0x79, 0x70, 0x65)
	o = msgp.AppendInt32(o, int32(z.Type))
	// string "To"
	o = append(o, 0xa2, 0x54, 0x6f)
	o = msgp.AppendUint64(o, z.To)
	// string "From"
	o = append(o, 0xa4, 0x46, 0x72, 0x6f, 0x6d)
	o = msgp.AppendUint64(o, z.From)
	// string "Term"
	o = append(o, 0xa4, 0x54, 0x65, 0x72, 0x6d)
	o = msgp.AppendUint64(o, z.Term)
	// string "LogTerm"
	o = append(o, 0xa7, 0x4c, 0x6f, 0x67, 0x54, 0x65, 0x72, 0x6d)
	o = msgp.AppendUint64(o, z.LogTerm)
	// string "Index"
	o = append(o, 0xa5, 0x49, 0x6e, 0x64, 0x65, 0x78)
	o = msgp.AppendUint64(o, z.Index)
	// string "Entries"
	o = append(o, 0xa7, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Entries)))
	for za0001 := range z.Entries {
		o, err = z.Entries[za0001].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Entries", za0001)
			return
		}
	}
	// string "Commit"
	o = append(o, 0xa6, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74)
	o = msgp.AppendUint64(o, z.Commit)
	// string "Vote"
	o = append(o, 0xa4, 0x56, 0x6f, 0x74, 0x65)
	o = msgp.AppendUint64(o, z.Vote)
	// string "Snapshot"
	o = append(o, 0xa8, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74)
	if z.Snapshot == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = z.Snapshot.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Snapshot")
			return
		}
	}
	// string "Reject"
	o = append(o, 0xa6, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74)
	o = msgp.AppendBool(o, z.Reject)
	// string "RejectHint"
	o = append(o, 0xaa, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x48, 0x69, 0x6e, 0x74)
	o = msgp.AppendUint64(o, z.RejectHint)
	// string "Context"
	o = append(o, 0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74)
	o = msgp.AppendBytes(o, z.Context)
	// string "Responses"
	o = append(o, 0xa9, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Responses)))
	for za0002 := range z.Responses {
		o, err = z.Responses[za0002].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Responses", za0002)
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Message) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Type":
			{
				var zb0002 int32
				zb0002, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Type")
					return
				}
				z.Type = MessageType(zb0002)
			}
		case "To":
			z.To, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "To")
				return
			}
		case "From":
			z.From, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "From")
				return
			}
		case "Term":
			z.Term, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Term")
				return
			}
		case "LogTerm":
			z.LogTerm, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LogTerm")
				return
			}
		case "Index":
			z.Index, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Index")
				return
			}
		case "Entries":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Entries")
				return
			}
			if cap(z.Entries) >= int(zb0003) {
				z.Entries = (z.Entries)[:zb0003]
			} else {
				z.Entries = make([]Entry, zb0003)
			}
			for za0001 := range z.Entries {
				bts, err = z.Entries[za0001].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Entries", za0001)
					return
				}
			}
		case "Commit":
			z.Commit, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Commit")
				return
			}
		case "Vote":
			z.Vote, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Vote")
				return
			}
		case "Snapshot":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.Snapshot = nil
			} else {
				if z.Snapshot == nil {
					z.Snapshot = new(Snapshot)
				}
				bts, err = z.Snapshot.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Snapshot")
					return
				}
			}
		case "Reject":
			z.Reject, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Reject")
				return
			}
		case "RejectHint":
			z.RejectHint, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "RejectHint")
				return
			}
		case "Context":
			z.Context, bts, err = msgp.ReadBytesBytes(bts, z.Context)
			if err != nil {
				err = msgp.WrapError(err, "Context")
				return
			}
		case "Responses":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Responses")
				return
			}
			if cap(z.Responses) >= int(zb0004) {
				z.Responses = (z.Responses)[:zb0004]
			} else {
				z.Responses = make([]Message, zb0004)
			}
			for za0002 := range z.Responses {
				bts, err = z.Responses[za0002].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Responses", za0002)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Message) Msgsize() (s int) {
	s = 1 + 5 + msgp.Int32Size + 3 + msgp.Uint64Size + 5 + msgp.Uint64Size + 5 + msgp.Uint64Size + 8 + msgp.Uint64Size + 6 + msgp.Uint64Size + 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Entries {
		s += z.Entries[za0001].Msgsize()
	}
	s += 7 + msgp.Uint64Size + 5 + msgp.Uint64Size + 9
	if z.Snapshot == nil {
		s += msgp.NilSize
	} else {
		s += z.Snapshot.Msgsize()
	}
	s += 7 + msgp.BoolSize + 11 + msgp.Uint64Size + 8 + msgp.BytesPrefixSize + len(z.Context) + 10 + msgp.ArrayHeaderSize
	for za0002 := range z.Responses {
		s += z.Responses[za0002].Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MessageType) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 int32
		zb0001, err = dc.ReadInt32()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = MessageType(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z MessageType) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteInt32(int32(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z MessageType) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendInt32(o, int32(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessageType) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 int32
		zb0001, bts, err = msgp.ReadInt32Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = MessageType(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z MessageType) Msgsize() (s int) {
	s = msgp.Int32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Snapshot) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Data":
			z.Data, err = dc.ReadBytes(z.Data)
			if err != nil {
				err = msgp.WrapError(err, "Data")
				return
			}
		case "Metadata":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Metadata")
				return
			}
			for zb0002 > 0 {
				zb0002--
				field, err = dc.ReadMapKeyPtr()
				if err != nil {
					err = msgp.WrapError(err, "Metadata")
					return
				}
				switch msgp.UnsafeString(field) {
				case "ConfState":
					err = z.Metadata.ConfState.DecodeMsg(dc)
					if err != nil {
						err = msgp.WrapError(err, "Metadata", "ConfState")
						return
					}
				case "Index":
					z.Metadata.Index, err = dc.ReadUint64()
					if err != nil {
						err = msgp.WrapError(err, "Metadata", "Index")
						return
					}
				case "Term":
					z.Metadata.Term, err = dc.ReadUint64()
					if err != nil {
						err = msgp.WrapError(err, "Metadata", "Term")
						return
					}
				default:
					err = dc.Skip()
					if err != nil {
						err = msgp.WrapError(err, "Metadata")
						return
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Snapshot) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Data"
	err = en.Append(0x82, 0xa4, 0x44, 0x61, 0x74, 0x61)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Data)
	if err != nil {
		err = msgp.WrapError(err, "Data")
		return
	}
	// write "Metadata"
	err = en.Append(0xa8, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61)
	if err != nil {
		return
	}
	// map header, size 3
	// write "ConfState"
	err = en.Append(0x83, 0xa9, 0x43, 0x6f, 0x6e, 0x66, 0x53, 0x74, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	err = z.Metadata.ConfState.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Metadata", "ConfState")
		return
	}
	// write "Index"
	err = en.Append(0xa5, 0x49, 0x6e, 0x64, 0x65, 0x78)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Metadata.Index)
	if err != nil {
		err = msgp.WrapError(err, "Metadata", "Index")
		return
	}
	// write "Term"
	err = en.Append(0xa4, 0x54, 0x65, 0x72, 0x6d)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Metadata.Term)
	if err != nil {
		err = msgp.WrapError(err, "Metadata", "Term")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Snapshot) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Data"
	o = append(o, 0x82, 0xa4, 0x44, 0x61, 0x74, 0x61)
	o = msgp.AppendBytes(o, z.Data)
	// string "Metadata"
	o = append(o, 0xa8, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61)
	// map header, size 3
	// string "ConfState"
	o = append(o, 0x83, 0xa9, 0x43, 0x6f, 0x6e, 0x66, 0x53, 0x74, 0x61, 0x74, 0x65)
	o, err = z.Metadata.ConfState.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Metadata", "ConfState")
		return
	}
	// string "Index"
	o = append(o, 0xa5, 0x49, 0x6e, 0x64, 0x65, 0x78)
	o = msgp.AppendUint64(o, z.Metadata.Index)
	// string "Term"
	o = append(o, 0xa4, 0x54, 0x65, 0x72, 0x6d)
	o = msgp.AppendUint64(o, z.Metadata.Term)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Snapshot) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Data":
			z.Data, bts, err = msgp.ReadBytesBytes(bts, z.Data)
			if err != nil {
				err = msgp.WrapError(err, "Data")
				return
			}
		case "Metadata":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Metadata")
				return
			}
			for zb0002 > 0 {
				zb0002--
				field, bts, err = msgp.ReadMapKeyZC(bts)
				if err != nil {
					err = msgp.WrapError(err, "Metadata")
					return
				}
				switch msgp.UnsafeString(field) {
				case "ConfState":
					bts, err = z.Metadata.ConfState.UnmarshalMsg(bts)
					if err != nil {
						err = msgp.WrapError(err, "Metadata", "ConfState")
						return
					}
				case "Index":
					z.Metadata.Index, bts, err = msgp.ReadUint64Bytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Metadata", "Index")
						return
					}
				case "Term":
					z.Metadata.Term, bts, err = msgp.ReadUint64Bytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Metadata", "Term")
						return
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						err = msgp.WrapError(err, "Metadata")
						return
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Snapshot) Msgsize() (s int) {
	s = 1 + 5 + msgp.BytesPrefixSize + len(z.Data) + 9 + 1 + 10 + z.Metadata.ConfState.Msgsize() + 6 + msgp.Uint64Size + 5 + msgp.Uint64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *SnapshotMetadata) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ConfState":
			err = z.ConfState.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "ConfState")
				return
			}
		case "Index":
			z.Index, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Index")
				return
			}
		case "Term":
			z.Term, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Term")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *SnapshotMetadata) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "ConfState"
	err = en.Append(0x83, 0xa9, 0x43, 0x6f, 0x6e, 0x66, 0x53, 0x74, 0x61, 0x74, 0x65)
	if err != nil {
		return
	}
	err = z.ConfState.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "ConfState")
		return
	}
	// write "Index"
	err = en.Append(0xa5, 0x49, 0x6e, 0x64, 0x65, 0x78)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Index)
	if err != nil {
		err = msgp.WrapError(err, "Index")
		return
	}
	// write "Term"
	err = en.Append(0xa4, 0x54, 0x65, 0x72, 0x6d)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Term)
	if err != nil {
		err = msgp.WrapError(err, "Term")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SnapshotMetadata) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "ConfState"
	o = append(o, 0x83, 0xa9, 0x43, 0x6f, 0x6e, 0x66, 0x53, 0x74, 0x61, 0x74, 0x65)
	o, err = z.ConfState.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "ConfState")
		return
	}
	// string "Index"
	o = append(o, 0xa5, 0x49, 0x6e, 0x64, 0x65, 0x78)
	o = msgp.AppendUint64(o, z.Index)
	// string "Term"
	o = append(o, 0xa4, 0x54, 0x65, 0x72, 0x6d)
	o = msgp.AppendUint64(o, z.Term)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SnapshotMetadata) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ConfState":
			bts, err = z.ConfState.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "ConfState")
				return
			}
		case "Index":
			z.Index, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Index")
				return
			}
		case "Term":
			z.Term, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Term")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SnapshotMetadata) Msgsize() (s int) {
	s = 1 + 10 + z.ConfState.Msgsize() + 6 + msgp.Uint64Size + 5 + msgp.Uint64Size
	return
}
